apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- resources/serviceaccount.yaml
- resources/rolebindings.yaml
- resources/deployment.yaml

namespace: operator-envinit